version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
      actions-major:
        patterns: ["*"]
        update-types: [major]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
      npm-major:
        patterns: ["*"]
        update-types: [major]
    commit-message:
      prefix: chore
      include: scope
